=== n434p/WORK.NET/HOMEWORK/HTML/XML/contact.dtd
<!ELEMENT cell EMPTY>
<!ELEMENT name (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT contact (name, cell, location)> 
<!ELEMENT contactsBook (contact+) >

<!ENTITY test 'TEst text'>

<!ATTLIST contact
  sex(male|female) 'male'>
<!ATTLIST location
  type CDATA #REQUIRED>
<!ATTLIST cell
  number CDATA #REQUIRED>

=== n434p/WORK.NET/HOMEWORK/HTML/XML/contactsBook.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE contactsBook SYSTEM "contact.dtd">
<?xml-stylesheet type="text/css" href="styleBook.css"?>
<contactsBook>
  <contact>
    <name>Petrov Petr</name>
    <cell number="055555555"/>
    <location type="afads"></location>
  </contact>
  <!--<contact>
    <name>Ivanov Ivan</name>
    <cell number="066666666"/>
  </contact>
  <contact>
    <name>New Guy</name>
    <cell>00000000</cell>
  </contact>-->
  <contact sex="male">
    <name>kjlkjlkjl</name>
    <cell number="0888888888"></cell>
    <location type="unknown location"></location>
    
  </contact>
  
</contactsBook>
