=== n434p/WORK.NET/HOMEWORK/HTML/XML/myXml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="test">
    <xs:restriction base="xs:string">
      <xs:pattern value="\+380[0-9]{9}"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="myaddress">
    <xs:sequence>
      <xs:element name="country">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="code" type ="xs:string" use="required"></xs:attribute>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="street" type="xs:string"/>
      <xs:element name="house" type="xs:string"/>
      <xs:element name="appartment" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="message">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="to" type="test" maxOccurs="unbounded"/>
        <xs:element name="from" type="test"/>
        <xs:element name="date" type="xs:dateTime"/>
        <xs:element name="header">
          <xs:simpleType>
            <xs:restriction base ="xs:string">
              <xs:enumeration value="Invite"/>
              <xs:enumeration value="Advertise"/>
              <xs:enumeration value="Spam"/>
              <xs:enumeration value="Work"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="text">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:whiteSpace value="replace"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="address" type="myaddress"/>

        <xs:element name="address2" >
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="myaddress">
                <xs:sequence>
                  <xs:element name ="app" type ="xs:string"/>
                </xs:sequence>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>

        
        <xs:element name="zipcode">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="10000"/>
              <xs:maxInclusive value="99999"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="operator">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="letter">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="event" type="xs:string"/>
              <xs:element name="date" type="xs:date"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:any></xs:any>
        
      </xs:sequence>
    </xs:complexType>
      </xs:element>
</xs:schema>

=== n434p/WORK.NET/HOMEWORK/HTML/XML/myxml.xml
<?xml version="1.0" encoding="utf-8"?>
<message xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="myxml.xsd">
  <to>+380501232525</to>
  <from>+380991251255</from>
  <date>2013-11-03T11:11:11</date>
  <header>Spam</header>
  <text>Test   success   !</text>
  <address>
    <country></country>
    <city></city>
    <street></street>
    <house></house>
    <appartment></appartment>
  </address>
  <address2>
    <country></country>
    <city></city>
    <street></street>
    <house></house>
    <appartment></appartment>
    <app></app>
  </address2>
  <zipcode>12130</zipcode>

</message>
