<?xml version="1.0" encoding="utf-8"?>
<!--<!DOCTYPE contactsBook SYSTEM "recipe.dtd">-->

<!DOCTYPE contactsBook [
<!ELEMENT info (#PCDATA)>
<!ELEMENT ingredient (#PCDATA) >
<!ELEMENT recipe (info,ingredient+)>
<!ELEMENT recipeBook (recipe+)>

<!ATTLIST recipe
  name CDATA #REQUIRED
  >
<!ATTLIST cookM
  cookMode (roast|cook|boil|cut_boxes|slice|add) 'add' #REQUIRED
  >
  
<!ATTLIST ingredient
  cookMode (roast|cook|boil|cut_boxes|slice|add) 'cook'
  time CDATA #REQUIRED
  measure (mg|g|kg|ml|l|spoon) 'g'
  quantity CDATA #REQUIRED
  >
]>


<?xml-stylesheet type="text/css" href="recipeBook.css"?>
<recipeBook>
  <recipe name="tea">
    <info>launch</info>
    <ingredient measure="spoon" quantity="2" cookMode="add" time="">sugar</ingredient>

    <ingredient measure="spoon" quantity="2" cookMode="add" time="">tea</ingredient>

    <ingredient measure="ml" quantity="200" cookMode="boil" time="5 min">water</ingredient>
    
  </recipe>
</recipeBook>
